services:
  ########################
  #   BACKEND (FastAPI)  #
  ########################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    network_mode: bridge
    ports:
      - "127.0.0.1:8000:8000"

  ########################
  #   FRONTEND (Vue.js)  #
  ########################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    network_mode: bridge
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
